plugins {
    id 'java'
    id 'igse' version '1.0'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'jacoco'
    id 'com.gorylenko.gradle-git-properties' version '2.4.1'
    //id 'org.ajoberstar.grgit' version "5.0.0-rc.3"

    //id 'org.unbroken-dome.test-sets' version '4.0.0'
    // id 'docker-compose'
}

springBoot {
    buildInfo()
}
group = 'com.igse'
//version = "${igseVersion}${igse.suffix()}"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
}

ext['resilience4jVersion'] = '2.1.0'
ext['spring-framework.version'] = '6.1.13'
ext['tomcat.version'] = '10.1.25'


dependencies {
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation "org.springframework.boot:spring-boot-starter-aop"

    testImplementation('org.springframework.boot:spring-boot-starter-test:3.2.5',
            'io.projectreactor:reactor-test:3.6.5',
            "com.github.tomakehurst:wiremock-jre8-standalone:2.35.2",
            'io.rest-assured:rest-assured:5.3.1',
            'org.hamcrest:hamcrest:2.1',
            'org.awaitility:awaitility:4.0.3')

    /*implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'*/
    implementation("io.jsonwebtoken:jjwt-api:0.11.5",
            "io.jsonwebtoken:jjwt-impl:0.11.5",
            "io.jsonwebtoken:jjwt-jackson:0.11.5")

    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok'

    runtimeOnly 'com.mysql:mysql-connector-j:8.3.0'
    implementation 'org.flywaydb:flyway-mysql'

    //implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j:3.1.1'

    implementation 'net.javacrumbs.shedlock:shedlock-spring:5.8.0'
    implementation 'net.javacrumbs.shedlock:shedlock-provider-jdbc-template:5.8.0'


    implementation 'io.spring.gradle:dependency-management-plugin:1.1.6'
    //implementation 'com.github.spotbugs.snom:spotbugs-gradle-plugin:5.0.15'
    // implementation 'com.gorylenko.gradle-git-properties:gradle-git-properties:2.4.2'

    implementation 'org.apache.commons:commons-text:1.12.0'
    implementation 'org.apache.commons:commons-lang3'

    implementation 'com.igse:igse-common:1.1'
    //implementation 'com.vladmihalcea:hibernate-types-52:2.21.1'

    implementation 'org.bouncycastle:bcprov-jdk18on:1.79'

    implementation "io.github.resilience4j:resilience4j-spring-boot3:${resilience4jVersion}"
    implementation "io.github.resilience4j:resilience4j-ratelimiter:${resilience4jVersion}"
    implementation "io.github.resilience4j:resilience4j-retry:${resilience4jVersion}"
    implementation "io.github.resilience4j:resilience4j-bulkhead:${resilience4jVersion}"
    implementation "io.github.resilience4j:resilience4j-cache:${resilience4jVersion}"
    implementation "io.github.resilience4j:resilience4j-timelimiter:${resilience4jVersion}"
}


tasks.withType(Test) {
    jvmArgs(["-Dspring.output.ansi.enabled=ALWAYS", "-Dspring.profiles.active=dev"])
    finalizedBy jacocoTestReport
    useJUnitPlatform()
}


bootJar {
    destinationDirectory.set(file("D:\\Project\\buildJars"))
}

bootRun {
    jvmArgs(["-Dspring.output.ansi.enabled=ALWAYS", "-Dspring.profiles.active=dev"])
}
jacocoTestReport {
    reports {
        xml.required = false
        html.outputLocation = layout.buildDirectory.dir('reports/jacoco')
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    "com/igse/dto/**",
                    "com/igse/entity/**"
            ])
        }))
    }
}
gitProperties {
    keys = [
            'git.branch',
            'git.commit.id',
            'git.build.version'

            /*
             'git.dirty',
            'git.commit.message.full',
            'git.commit.user.name',
            'git.commit.user.email',
            'git.remote.origin.url',
            'git.build.host'
            */
    ]
}

configurations.runtimeClasspath.resolutionStrategy.activateDependencyLocking()