pluginManagement {
	repositories {
		maven {
			url = uri("https://maven.pkg.github.com/talhaansari04/igse-plugin")
			credentials {
				username =  System.getenv('GITHUB_USERNAME')
				password =  System.getenv('GITHUB_TOKEN')
			}
		}
		maven { url 'https://repo.spring.io/milestone' }
		maven { url 'https://repo.spring.io/snapshot' }
		mavenLocal()
		gradlePluginPortal()
	}
}

rootProject.name = 'igse-authentication'
def modules = ["performance"]
include(modules as String[])
modules.each { name ->
	project(":${name}").projectDir = "$rootDir/$name/" as File
}
