eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#spring:
#  kafka:
#    bootstrap-servers: localhost:9092

services:
  igse:
    core:
      endpoint: http://localhost:9701
    payment:
      endpoint: http://localhost:8080/igse-payment
  kafka:
    regisTopics: v1.dev.regi
    groupId: "default-dev"

service:
  kafka:
    enable: false
    wallet:
      topic: "wallet.v1"
      groupId: "wallet-dev-A1"
logging:
  pattern:
    console: "%clr(IST=){faint}%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z', UTC}){faint} [%t] %clr(APP=){faint}%clr(${spring.application.name:null}){yellow} %clr(LEVEL=){faint}%clr(${LOG_LEVEL_PATTERN:%p}) %clr(CLASS=){faint}%clr(%logger{26}){cyan} %clr(X-Correlation-Id=){faint}%clr(%X{X-Correlation-Id:-null}){reverse} | %m%n%ex"
  level:
    org:
      apache:
        kafka: off
spring:
  sql:
    init:
      mode: ALWAYS
      data-locations:
        - classpath:sql/cleanUp.sql
        - classpath:sql/dashboard_admin.sql


