eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#spring:
#  kafka:
#    bootstrap-servers: localhost:9092

services:
  igse:
    core:
      endpoint: http://localhost:8080/igse/core
    payment:
      endpoint: http://localhost:8080/igse-payment
  kafka:
    regisTopics: v1.dev.regi
    groupId: "default-dev"

service:
  kafka:
    enable: false
    wallet:
      topic: "wallet.v1"
      groupId: "wallet-dev-A1"
logging:
  level:
    org:
      apache:
        kafka: off