#-----Default admin id and pass------#
igse:
  admin:
    id: gse@shangrila.gov.un
    pass: gse@energy
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
server:
  servlet:
    context-path: /igse/auth
  port: 6000
spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: igse-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://127.0.0.1:3306/igse-admin
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev
services:
  kafka:
    regisTopics: v1.dev.regi
    groupId: "default-dev"




