#-----Default admin id and pass------#
igse:
  admin:
    day: 0.34
    night: 0.2
    gas: 0.1
    id: gse@shangrila.gov.un
    pass: gse@energy
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
server:
  servlet:
    context-path: /igse/auth
  port: 6000
spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: igse-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://127.0.0.1:3306/igse-admin
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev
services:
  kafka:
    regisTopics: v1.dev.regi
    groupId: "default-dev"

infrastructure:
  services:
    igse_payment:
      endpoint: ${services.igse.payment.endpoint}
      walletDetailPath: /wallet/v1/{customerId}/info
    igse_core:
      endpoint: ${services.igse.core.endpoint}
      meterDetailPath: /admin/meter/price
      changePricePath: /admin/change/price
      voucherDetailsPath: /voucher/
      saveVoucherPath: /voucher/save