#-----Default admin id and pass------#
igse:
  admin:
    id: gse@shangrila.gov.un
    pass: gse@energy

management:
  info:
    git:
      enabled: true
      mode: full
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
info:
  build:
    version: #version#

server:
  port: 6000
  servlet:
    context-path: /igse-auth
spring:
  application:
    name: igse-auth
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/igse_admin
    username: igse
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: springBootJpaHikari
      max-lifetime: 2000000
      connection-timeout: 5000
      connection-test-query: select 1
      connection-init-sql: select 1
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

services:
  kafka:
    enable: true
    regisTopics: v1.dev.regi
    groupId: "default-dev"

infrastructure:
  services:
    igse_payment:
      endpoint: ${services.igse.payment.endpoint}
      walletDetailPath: /wallet/v1/{customerId}/info
    igse_core:
      endpoint: ${services.igse.core.endpoint}
      meterDetailPath: /admin/meter/price
      changePricePath: /admin/change/price
      voucherDetailsPath: /voucher/
      saveVoucherPath: /voucher/save
logging:
  pattern:
    console: "%clr(IST=){faint}%clr(%d{yyyy-MM-dd'|'HH:mm:ss, Asia/Kolkata}){faint} [%t] %clr(APP=){faint}%clr(${spring.application.name:null}){yellow} %clr(LEVEL=){faint}%clr(${LOG_LEVEL_PATTERN:%p}) %clr(CLASS=){faint}%clr(%logger{26}){cyan} %clr(CID:){faint}%clr(%X{X-Correlation-Id:-}){reverse} | %m%n%ex"
  level:
    org:
      apache:
        kafka: off
poller:
  outOfBox:
    cron: "0 0/1 * * * ?"
    enable: true
meter:
  fixed-price:
    dayReading: 100.00
    nightReading: 250.00
    gasReading: 800.00

resilience4j.circuitbreaker:
  instances:
    wallet:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
