plugins {
    id 'java'
    id 'scala'
    id 'maven-publish'
    id 'io.gatling.gradle' version '3.13.1'
}
compileScala.targetCompatibility = 17
ScalaCompileOptions.metaClass.useAnt = false

group = 'com.igse'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    //testImplementation 'io.gatling:gatling-http-java:3.13.1'
    implementation "io.gatling.highcharts:gatling-charts-highcharts:3.6.1"
    implementation "io.gatling:gatling-test-framework:3.6.1"
}

task loadTest(dependsOn: ['compileTestScala', 'processTestResources']) {
    doLast {
        javaexec {
            main = 'io.gatling.app.Gatling'
            classpath = sourceSets.test.output + sourceSets.test.runtimeClasspath
            args '-sf', 'build/classes/main',
                    '-df', 'src/main/resources',
                    '-s', 'com.igse.PerformanceTests',
                    '-rf', "$buildDir/reports/gatling"
        }
    }
}
