plugins {
    id 'java'
    id 'scala'
    id 'maven-publish'
    id 'io.gatling.gradle' version '3.10.3'
}

compileScala.targetCompatibility = 21
ScalaCompileOptions.metaClass.useAnt = false

group = 'com.igse'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "io.gatling.highcharts:gatling-charts-highcharts:3.10.3" // Updated version
    implementation "io.gatling:gatling-test-framework:3.10.3" // Updated version
    implementation "org.scala-lang:scala-library:2.13.12" // Ensure Scala version compatibility
}

task loadTest(dependsOn: ['compileTestScala', 'processTestResources']) {
    doLast {
        javaexec {
            main = 'io.gatling.app.Gatling'
            classpath = sourceSets.test.output + sourceSets.test.runtimeClasspath
            args '-sf', 'build/classes/main',
                    '-df', 'src/main/resources',
                    '-s', 'com.igse.PerformanceTests',
                    '-rf', "$rootProject.layout.buildDirectory/reports/gatling"
        }
    }
}