# environment specific
host="http://localhost:6000"

# resource paths
uri-get-employee="/igse-auth/v1/login"
uri-health="igse/auth/actuator/info"


# test parameters
num-users=1000
user-ramp-seconds=2
test-duration-seconds=3
