name: CD

on:
  push:
    tags:
      - 'azure.standard.dev.*'
      - 'prod.standard.*'
env:
  environment: ${{ github.ref_name | split('.')[2] }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch All Tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get Latest Tag Subject environment ${{ env.environment }}
        id: get_tag_subject
        run: |
          TAG_SUBJECT=$(git tag --sort=-creatordate | head -n 1 | xargs -I {} git tag -l --format='%(contents:subject)' {})
          echo "::set-output name=tag_subject::$TAG_SUBJECT"

      - name: Print Latest Tag Subject
        run: |
          echo "Latest tag subject: ${{ steps.get_tag_subject.outputs.tag_subject }}"

      - name: Print Tag Message
        if: startsWith(github.ref, 'refs/tags/dev.standard.') || startsWith(github.ref, 'refs/tags/prod.dev.standard.')
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "The latest tag is: $TAG_NAME"
          if [[ "$TAG_NAME" == dev.* ]]; then
            echo "Stage tag pushed"
          elif [[ "$TAG_NAME" == prod.* ]]; then
            echo "Prod tag pushed"
          else
            echo "Unknown tag pushed $TAG_NAME"
          fi

      - name: Set TAG_NAME Environment Variable
        id: set_tag_name
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Github name: ${{ github.ref_name }}"
          echo "GitHub event: ${{ github.event_name }}"

      - name: Set Partial Tag Name
        id: set_partial_tag_name
        run: echo "THIRD_INDEX_VALUE=$(echo ${GITHUB_REF_NAME} | cut -d'.' -f3)" >> $GITHUB_ENV

      - name: Extract and Use Tag Name - ${{ env.PARTIAL_TAG_NAME }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          IFS='.' read -r -a TAG_ARRAY <<< "$TAG_NAME"
          if [ ${#TAG_ARRAY[@]} -gt 1 ]; then
            echo "Value at index 1: ${TAG_ARRAY[1]}"
          else
            echo "Tag name does not have enough parts"
          fi