name: CI

on:
  push:
    branches:
      - 'feature*'

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Deploy App
        id: deploy
        run: |
          echo "Running integration tests..."

      - name: Step 2 - Run Integration Tests
        id: integration_test
        if: ${{ steps.deploy.outcome == 'success' }}
        run: |
          echo "Running integration tests..."
          exit 1  # Fail the job for demonstration purposes


      - name: Step 3 - Cleanup
        if: success() || failure()
        run: |
          if [ "${{ steps.deploy.outcome }}" = "failure" ]; then
            echo "Script output is bad, failing the job."
            exit 1
          else
            echo "Script output is good, continuing."
          fi

      - name: Step 4 - Tag the commit
        if: ${{ steps.deploy.outcome == 'success' }} && ${{ steps.integration_test.outcome == 'success' }}
        run: |
          echo "Tagging the commit..."