name: CI

on:
  push:
    branches:
      - 'feature*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Environment Setup
        run: |
          echo "Running integration tests..."
  tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "talhaansari04"
          git config --global user.email "talhaansari61@gmail.com"

      - name: Development Tag Creation
        env:
          AUTHOR: ${{ github.event.pusher.name }}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
            COMMIT_SHORT=${SHA:0:7}
            TAG_NAME="dev.standard.dev.${{github.run_number}}.${COMMIT_SHORT}.${AUTHOR}"
            git tag -a ${TAG_NAME} -m "created_by_$AUTHOR"
            git push origin ${TAG_NAME}