name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: echo "Deploying to ${{ inputs.environment }}"

      - name: Common Deployment Step
        run: |
          echo "Running common deployment steps for ${{ inputs.environment }}"

      - name: Deploy to Environment
        if: inputs.environment == 'dev'
        run: |
          echo "Deploying to DEV environment"

      - name: Deploy to Stage
        if: inputs.environment == 'stage'
        run: |
          echo "Deploying to STAGE environment"

      - name: Deploy to Prod
        if: inputs.environment == 'prod'
        run: |
          echo "Deploying to PROD environment"
