name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: echo "Deploying to ${{ inputs.environment }}"

      - name: Common Deployment Step
        run: |
          echo "Running common deployment steps for ${{ inputs.environment }}"